c = clock;
folder_name = [num2str(c(1)), ... % year
               '_', ...
               num2str(c(2)), ... % month
               '_', ...
               num2str(c(3)), ... % day
               '_', ...
               num2str(c(4)), ... % hour
               '_', ...
               num2str(c(5)), ... % minute
               '_', ...
               num2str(fix(c(6)))] % second